# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

# Configure Kubernetes provider
# provider "kubernetes" {
#   config_path = data.terraform_remote_state.bootstrap.outputs.kubeconfig_path
# }

# # Configure Helm provider
# provider "helm" {
#   kubernetes {
#     config_path = data.terraform_remote_state.bootstrap.outputs.kubeconfig_path
#   }
# }

# # Configure GitHub provider (uses GITHUB_TOKEN env var)
# provider "github" {
# }

# # ============================================================================
# # Reference Previous Stack Outputs
# # ============================================================================

# data "terraform_remote_state" "bootstrap" {
#   backend = "local"
#   config = {
#     path = "../04-bootstrap/terraform.tfstate"
#   }
# }

# # ============================================================================
# # GitOps Deployment (FluxCD)
# # ============================================================================

# locals {
#   git_url = var.git_url != "" ? var.git_url : "${var.git_base_url}/${var.git_org_or_username}/${var.git_repository}.git"
# }

# provider "flux" {
#   kubernetes = {
#     config_path = data.terraform_remote_state.bootstrap.outputs.kubeconfig_path
#   }
#   git = {
#     url = local.git_url
#     http = {
#       username = var.git_username
#       password = var.git_token
#     }
#   }
# }

# module "fluxcd" {
#   count  = var.deploy_fluxcd ? 1 : 0
#   source = "../../../modules/fluxcd"
  
#   git_base_url            = var.git_base_url
#   git_token               = var.git_token
#   git_org_or_username     = var.git_org_or_username
#   git_repository          = var.git_repository
#   git_username            = var.git_username
#   talos_k8s_cluster_domain = var.talos_k8s_cluster_domain
#   fluxcd_cluster_path     = var.fluxcd_cluster_path
# }

# # ============================================================================
# # ArgoCD Deployment (Optional)
# # ============================================================================

# module "argocd" {
#   count  = var.deploy_argocd ? 1 : 0
#   source = "../../../modules/argocd"
  
#   providers = {
#     helm       = helm
#     kubernetes = kubernetes
#   }
  
#   argocd_namespace = var.argocd_namespace
#   argocd_version   = var.argocd_version
  
#   # Git repository configuration for ArgoCD
#   git_repository = var.git_repository
#   git_owner      = var.git_org_or_username
#   git_token      = var.git_token
# }
