# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

locals {
  talos_k8s_cluster_endpoint = "https://api.${var.talos_k8s_cluster_vip_domain}:${var.talos_k8s_cluster_endpoint_port}"
  
  # Collect all VMs that need CD-ROM ejection
  all_vms = concat(
    data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network,
    data.terraform_remote_state.vms.outputs.talos_worker_network
  )
}

# ============================================================================
# Reference Previous Stack Outputs
# ============================================================================

data "terraform_remote_state" "vms" {
  backend = "local"
  config = {
    path = "../02-vms/terraform.tfstate"
  }
}

data "terraform_remote_state" "talos_config" {
  backend = "local"
  config = {
    path = "../03-talos-config/terraform.tfstate"
  }
}


# ============================================================================
# Bootstrap Talos Cluster
# ============================================================================

module "talos_bootstrap" {
  depends_on = []
  source = "../../../modules/talos/bootstrap"

  providers = {
    talos = talos
  }

  client_configuration   = data.terraform_remote_state.talos_config.outputs.client_configuration
  cluster_name           = var.talos_k8s_cluster_name
  control_plane_nodes    = data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network
  bootstrap_wait_duration = "120s"
}

