variable "talos_k8s_cluster_name" {
  type    = string
  default = "talos-cluster"
}

variable "talos_k8s_cluster_vip_domain" {
  type    = string
  default = "talos-cluster.local"
}

variable "talos_k8s_cluster_endpoint_port" {
  type    = number
  default = 6443
}

variable "talos_k8s_cluster_vip" {
  type = string
}

variable "talos_network_gateway" {
  type    = string
  default = "10.0.0.1"
}

variable "talos_network_ip_prefix" {
  type    = number
  default = 24
}

variable "talos_k8s_cluster_domain" {
  type    = string
  default = "cluster.local"
}

# Proxmox API variables are generated by Terramate
# See config/generate_providers.tm.hcl -> _generated_proxmox_vars.tm.tf
