variable "talos_k8s_cluster_name" {
  type    = string
  default = "talos-cluster"
}
variable "talos_network_ip_prefix" {
  type    = number
  default = 24
}

# Proxmox API variables are generated by Terramate
# See config/generate_providers.tm.hcl -> _generated_proxmox_vars.tm.tf
