# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

locals {
  talos_disk_image_locations = var.talos_disk_image_locations
}

# ============================================================================
# Create VMs (Control Plane)
# ============================================================================

module "control_plane_vms" {
  source = "../../../modules/vms/create_vms_control_plane"

  providers = {
    macaddress = macaddress
    proxmox    = proxmox
    time       = time
  }

  proxmox_nodes             = var.proxmox_nodes
  control_plane_first_id    = var.control_plane_first_id
  control_plane_first_ip    = var.control_plane_first_ip
  talos_network_dhcp        = var.talos_network_dhcp
  talos_network_cidr        = var.talos_network_cidr
  talos_network_gateway     = var.talos_network_gateway
  talos_iso_image_location  = ""  # Using disk images instead
  control_plane_name_prefix = var.control_plane_name_prefix

  # Image-based boot support
  talos_disk_image_locations = local.talos_disk_image_locations
}

# ============================================================================
# Create VMs (Workers)
# ============================================================================

module "workers_vms" {
  source = "../../../modules/vms/create_vms_workers"

  providers = {
    macaddress = macaddress
    proxmox    = proxmox
    time       = time
  }

  proxmox_nodes             = var.proxmox_nodes
  worker_node_first_id      = var.worker_node_first_id
  worker_node_first_ip      = var.worker_node_first_ip
  talos_network_dhcp        = var.talos_network_dhcp
  talos_network_cidr        = var.talos_network_cidr
  talos_network_gateway     = var.talos_network_gateway
  talos_iso_image_location  = ""  # Using disk images instead
  worker_node_name_prefix   = var.worker_node_name_prefix

  # Image-based boot support
  talos_disk_image_locations = local.talos_disk_image_locations
}
