# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

# Configure Proxmox provider
provider "proxmox" {
  endpoint  = var.proxmox_api_url
  api_token = "${var.proxmox_user}!${var.proxmox_api_token_id}=${var.proxmox_api_token_secret}"
  insecure  = true
  tmp_dir   = "/var/tmp"
  
  ssh {
    agent    = true
    username = var.proxmox_user
  }
}

locals {
  talos_iso_image_location = var.talos_iso_image_location
}

# ============================================================================
# Create VMs (Control Plane)
# ============================================================================

module "control_plane_vms" {
  source = "../../../modules/create_vms_control_plane"

  providers = {
    macaddress = macaddress
    proxmox    = proxmox
    time       = time
  }

  proxmox_nodes             = var.proxmox_nodes
  control_plane_first_id    = var.control_plane_first_id
  control_plane_first_ip    = var.control_plane_first_ip
  talos_network_dhcp        = var.talos_network_dhcp
  talos_network_cidr        = var.talos_network_cidr
  talos_network_gateway     = var.talos_network_gateway
  talos_iso_image_location  = local.talos_iso_image_location
  control_plane_name_prefix = var.control_plane_name_prefix
}

# ============================================================================
# Create VMs (Workers)
# ============================================================================

module "workers_vms" {
  source = "../../../modules/create_vms_workers"

  providers = {
    macaddress = macaddress
    proxmox    = proxmox
    time       = time
  }

  proxmox_nodes             = var.proxmox_nodes
  worker_node_first_id      = var.worker_node_first_id
  worker_node_first_ip      = var.worker_node_first_ip
  talos_network_dhcp        = var.talos_network_dhcp
  talos_network_cidr        = var.talos_network_cidr
  talos_network_gateway     = var.talos_network_gateway
  talos_iso_image_location  = local.talos_iso_image_location
  worker_node_name_prefix   = var.worker_node_name_prefix
}
