# Proxmox provider variables are generated by Terramate
# See config/generate_providers.tm.hcl -> _generated_proxmox_vars.tm.tf

# Common variables (proxmox_nodes, talos_network_cidr, talos_network_gateway) 
# are now generated by Terramate (see config/generate_common_vars.tm.hcl and config/generate_proxmox_nodes_var.tm.hcl)

variable "control_plane_first_id" {
  type    = number
  default = 8100
}

variable "control_plane_first_ip" {
  type    = number
  default = 161
}

variable "control_plane_name_prefix" {
  type    = string
  default = "talos-control-plane"
}

variable "worker_node_first_id" {
  type    = number
  default = 8200
}

variable "worker_node_first_ip" {
  type    = number
  default = 171
}

variable "worker_node_name_prefix" {
  type    = string
  default = "talos-worker-node"
}

variable "talos_network_dhcp" {
  type    = bool
  default = true
}

