# Proxmox provider variables are generated by Terramate
# See config/generate_providers.tm.hcl -> _generated_proxmox_vars.tm.tf

variable "proxmox_nodes" {
  description = "Proxmox servers on which the talos cluster will be deployed"
  type = map(object({
    control_planes = optional(list(object({
      name = optional(string)
      node_labels = optional(map(string), {})
      taints_enabled = optional(bool, true)
      network_bridge = optional(string, "vmbr0")
      mac_address = optional(string)
      cpu_type = optional(string, "host")
      cpu_sockets = optional(number, 1)
      cpu_cores = optional(number, 2)
      memory = optional(number, 8)
      boot_disk_size = optional(number, 0)
      boot_disk_storage_pool = string
      data_disks = optional(list(object({
        device_name = string
        mount_point = string
        size = number
        storage_pool = optional(string, "")
      })), [])
    })))

    workers = optional(list(object({
      name = optional(string)
      node_labels = optional(map(string), {})
      network_bridge = optional(string, "vmbr0")
      mac_address = optional(string)
      cpu_type = optional(string, "host")
      cpu_sockets = optional(number, 1)
      cpu_cores = optional(number, 2)
      memory = optional(number, 8)
      boot_disk_size = optional(number, 0)
      boot_disk_storage_pool = string
      data_disks = optional(list(object({
        device_name = string
        mount_point = string
        size = number
        storage_pool = optional(string, "")
      })), [])
    })))
  }))
}

variable "control_plane_first_id" {
  type    = number
  default = 8100
}

variable "control_plane_first_ip" {
  type    = number
  default = 161
}

variable "control_plane_name_prefix" {
  type    = string
  default = "talos-control-plane"
}

variable "worker_node_first_id" {
  type    = number
  default = 8200
}

variable "worker_node_first_ip" {
  type    = number
  default = 171
}

variable "worker_node_name_prefix" {
  type    = string
  default = "talos-worker-node"
}

variable "talos_network_dhcp" {
  type    = bool
  default = true
}

variable "talos_network_cidr" {
  type    = string
  default = "10.0.0.0/16"
}

variable "talos_network_gateway" {
  type    = string
  default = "10.0.0.1"
}

