# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

# Configure Kubernetes provider (uses KUBECONFIG env var or ~/.kube/config)
provider "kubernetes" {
}

# Configure Helm provider
provider "helm" {
}

# Configure Talos provider
provider "talos" {
}

# Configure Flux provider
provider "flux" {
}

# Configure GitHub provider (uses GITHUB_TOKEN env var)
provider "github" {
}

locals {
  talos_k8s_cluster_endpoint = "https://api.${var.talos_k8s_cluster_vip_domain}:${var.talos_k8s_cluster_endpoint_port}"
}

# ============================================================================
# Reference Previous Stack Outputs
# ============================================================================

data "terraform_remote_state" "vms" {
  backend = "local"
  config = {
    path = "../02-vms/terraform.tfstate"
  }
}

data "terraform_remote_state" "talos_config" {
  backend = "local"
  config = {
    path = "../03-talos-config/terraform.tfstate"
  }
}

# ============================================================================
# Apply Talos Configurations to Control Plane Nodes
# ============================================================================

module "apply_config_cp" {
  source = "../../../modules/talos/apply_config"

  providers = {
    talos = talos
  }

  machine_configuration = data.terraform_remote_state.talos_config.outputs.talos_config_cp
  client_configuration  = data.terraform_remote_state.talos_config.outputs.client_configuration
  nodes_network         = data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network
  
  cluster_domain      = var.talos_k8s_cluster_domain
  cluster_endpoint    = local.talos_k8s_cluster_endpoint
  network_gateway     = var.talos_network_gateway
  network_ip_prefix   = var.talos_network_ip_prefix
  cluster_vip         = var.talos_k8s_cluster_vip
}

# ============================================================================
# Apply Talos Configurations to Worker Nodes
# ============================================================================

module "apply_config_worker" {
  depends_on = [module.apply_config_cp]
  source = "../../../modules/talos/apply_config"

  providers = {
    talos = talos
  }

  machine_configuration = data.terraform_remote_state.talos_config.outputs.talos_config_worker
  client_configuration  = data.terraform_remote_state.talos_config.outputs.client_configuration
  nodes_network         = data.terraform_remote_state.vms.outputs.talos_worker_network
  
  cluster_domain      = var.talos_k8s_cluster_domain
  cluster_endpoint    = local.talos_k8s_cluster_endpoint
  network_gateway     = var.talos_network_gateway
  network_ip_prefix   = var.talos_network_ip_prefix
  cluster_vip         = var.talos_k8s_cluster_vip
}

# ============================================================================
# Bootstrap Talos Cluster
# ============================================================================

module "talos_bootstrap" {
  depends_on = [module.apply_config_cp, module.apply_config_worker]
  source = "../../../modules/talos/bootstrap"

  providers = {
    talos = talos
  }

  client_configuration   = data.terraform_remote_state.talos_config.outputs.client_configuration
  cluster_name           = var.talos_k8s_cluster_name
  control_plane_nodes    = data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network
  bootstrap_wait_duration = "120s"
}

# ============================================================================
# GitOps Deployment (FluxCD)
# ============================================================================

provider "flux" {
  kubernetes = {
    config_path = module.talos_bootstrap.kubeconfig_path
  }
  git = {
    url = "${var.git_base_url}/${var.git_org_or_username}/${var.git_repository}.git"
    http = {
      username = var.git_username
      password = var.git_token
    }
  }
}

module "fluxcd" {
  count      = var.deploy_fluxcd ? 1 : 0
  depends_on = [module.talos_bootstrap]
  source     = "../../../modules/fluxcd"
  
  git_base_url = var.git_base_url
  git_token = var.git_token
  git_org_or_username = var.git_org_or_username
  git_repository = var.git_repository
  git_username = var.git_username
  talos_k8s_cluster_domain = var.talos_k8s_cluster_domain
  fluxcd_cluster_path = var.fluxcd_cluster_path
}
