# Providers and versions are generated by Terramate
# See config/generate_providers.tm.hcl

# Configure Talos provider
provider "talos" {
}

locals {
  talos_k8s_cluster_endpoint = "https://api.${var.talos_k8s_cluster_vip_domain}:${var.talos_k8s_cluster_endpoint_port}"
  control_plane_ip_addresses = [for cp in data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network : cp.ip]
}

# ============================================================================
# Reference VMs Stack Outputs
# ============================================================================

data "terraform_remote_state" "vms" {
  backend = "local"
  config = {
    path = "../02-vms/terraform.tfstate"
  }
}

data "terraform_remote_state" "iso" {
  backend = "local"
  config = {
    path = "../01-talos-iso/terraform.tfstate"
  }
}

# ============================================================================
# Generate Cilium Manifests (Optional)
# ============================================================================

module "cilium" {
  count  = var.include_cilium_inline_manifests ? 1 : 0
  source = "../../../modules/generate_cilium_manifest"
  
  cilium_version = var.cilium_version  
  use_kube_proxy = var.use_kube_proxy     
  k8s_version = var.k8s_version
}

# ============================================================================
# Generate Talos Machine Secrets
# ============================================================================

module "talos_secrets" {
  source = "../../../modules/talos/secrets"

  providers = {
    talos = talos
  }

  talos_version = var.talos_version
}

# ============================================================================
# Generate Talos Machine Configurations (Control Plane)
# ============================================================================

module "talos_config_cp" {
  source = "../../../modules/talos/machine_config"

  providers = {
    talos = talos
  }

  machine_type = "controlplane"
  machine_secrets = module.talos_secrets.machine_secrets

  talos_k8s_cluster_name          = var.talos_k8s_cluster_name
  talos_k8s_cluster_vip_domain    = var.talos_k8s_cluster_vip_domain
  talos_k8s_cluster_endpoint_port = var.talos_k8s_cluster_endpoint_port
  talos_k8s_cluster_vip           = var.talos_k8s_cluster_vip
  talos_version                   = var.talos_version
  talos_network_gateway           = var.talos_network_gateway
  talos_name_servers              = var.talos_name_servers
  k8s_version                     = var.k8s_version
  talos_install_disk_device       = var.talos_install_disk_device
  talos_install_image_url         = var.talos_install_image_url != "" ? var.talos_install_image_url : data.terraform_remote_state.iso.outputs.talos_installer_image_url
  talos_control_plane_vms_network = data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network
  talos_k8s_cluster_domain        = var.talos_k8s_cluster_domain
  
  cilium_manifests                = length(module.cilium) > 0 ? module.cilium[0].cilium_manifests : ""
  include_cilium                  = length(module.cilium) > 0
}

# ============================================================================
# Generate Talos Machine Configurations (Worker)
# ============================================================================

module "talos_config_worker" {
  source = "../../../modules/talos/machine_config"

  providers = {
    talos = talos
  }

  machine_type = "worker"
  machine_secrets = module.talos_secrets.machine_secrets

  talos_k8s_cluster_name          = var.talos_k8s_cluster_name
  talos_k8s_cluster_vip_domain    = var.talos_k8s_cluster_vip_domain
  talos_k8s_cluster_endpoint_port = var.talos_k8s_cluster_endpoint_port
  talos_k8s_cluster_vip           = var.talos_k8s_cluster_vip
  talos_version                   = var.talos_version
  talos_network_gateway           = var.talos_network_gateway
  talos_name_servers              = var.talos_name_servers
  k8s_version                     = var.k8s_version
  talos_install_disk_device       = var.talos_install_disk_device
  talos_install_image_url         = var.talos_install_image_url != "" ? var.talos_install_image_url : data.terraform_remote_state.iso.outputs.talos_installer_image_url
  talos_control_plane_vms_network = data.terraform_remote_state.vms.outputs.talos_control_plane_vms_network
  talos_k8s_cluster_domain        = var.talos_k8s_cluster_domain
  
  include_cilium = false
}
