# Common variables (talos_version, k8s_version, cilium_version, talos_network_gateway, 
# talos_network_cidr, talos_k8s_cluster_domain, talos_k8s_cluster_vip_domain, 
# talos_k8s_cluster_endpoint_port, talos_k8s_cluster_vip) are now generated by Terramate
# See config/generate_common_vars.tm.hcl

variable "talos_k8s_cluster_name" {
  type    = string
  default = "talos-cluster"
}

variable "talos_name_servers" {
  type    = list(string)
  default = ["8.8.8.8", "1.1.1.1"]
}

variable "talos_install_disk_device" {
  type    = string
  default = "/dev/vda"  # VirtIO SCSI disk (virtio0 interface)
}

variable "talos_install_image_url" {
  type        = string
  default     = ""
  description = "URL of the Talos installer image. If not provided, it will be read from the 01-talos-image stack's outputs."
}

variable "use_kube_proxy" {
  type    = bool
  default = false
}

variable "include_cilium_inline_manifests" {
  type    = bool
  default = true
}
