# talos_version is now generated by Terramate (see config/generate_common_vars.tm.hcl)
# proxmox_nodes is now generated by Terramate (see config/generate_proxmox_nodes_var.tm.hcl)

variable "talos_architecture" {
  description = "CPU architecture for Talos image (amd64 or arm64)"
  type        = string
  default     = "amd64"
}

variable "talos_image_destination_storage_pool" {
  description = "Proxmox storage to store the Talos image (qcow2) on"
  type        = string
  default     = "local"
}

