# https://www.talos.dev/v1.5/kubernetes-guides/network/deploying-cilium/
k8sServiceHost: localhost
k8sServicePort: 7445

priorityClassName: "high-priority"

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

# https://docs.cilium.io/en/v1.14/network/bgp-control-plane/
bgpControlPlane:
  enabled: true

hubble:
  enabled: true
  relay:
    enabled: true
  ui:
    enabled: true

ipam:
  mode: kubernetes

kubeProxyReplacement: strict

operator:
  replicas: 1
  priorityClassName: "high-priority"

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
